ver = "0.4.1"

##### NOTES #####

# You might see: `flags="$(head -n 1 {} | cut -c 3-)"`
# This retrieves the flags passed on the first line of the test file.
#   `head -n 1 {}` extracts the first line.
#   `cut -c 3-` removes the first two characters, i.e., `//`.

##### COMPILATION TESTS #####

[[tests]]
name = "parsing bonsai ir"
paths = ["tests/bonsai/parsing/*.bonsai"]
cmd = """
./build/compiler -i {} -p core
"""

[[tests]]
name = "lowering bonsai ir"
paths = ["tests/bonsai/lower/*.bonsai"]
cmd = """
./build/compiler -i {}
"""

[[tests]]
name = "optimizing bonsai ir"
paths = ["tests/bonsai/opt/*.bonsai"]
cmd = """
./build/compiler -i {} -p default
"""

[[tests]]
name = "errors"
paths = ["tests/bonsai/error/*.bonsai"]
cmd = """
./build/compiler -i {}
"""

[[tests]]
name = "backends"
paths = ["tests/bonsai/backends/**/*.bonsai"]
cmd = """
flags="$(head -n 1 {} | cut -c 3-)"
./build/compiler -i {} $flags
"""

[[tests]]
name = "[correctness] llvm"
paths = ["tests/bonsai/correctness/llvm/*.bonsai"]
cmd = """
./build/compiler -i {} -b llvm -e
"""
