#pragma once

#include "CompilerOptions.h"
#include "IR/Program.h"
#include "Lower/Pass.h"

#include <string>

namespace bonsai {
namespace lower {

// Rewrites exported functions marked as exported and with struct return types
// to avoid issues when linking with C++ generated by an ABI-conforming
// compiler. For example,
//
//   S func [[export]] foo();
//   v = foo();
//
//  =>
//
//   void func [[export]] foo($r : mut S)
//   $r := build<S>();
//   foo($r);
//   v = $r
class ReturnToOutParameter : public Pass {
  public:
    constexpr std::string name() const override { return "rtop"; }

    ir::FuncMap run(ir::FuncMap functions,
                    const CompilerOptions &options) const override;
};

} // namespace lower
} // namespace bonsai
