name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

env:
  CMAKE_GENERATOR: Ninja
  CMAKE_BUILD_TYPE: Debug

jobs:
  build-and-test:
    # Currently we are only running this on mac-os. For multi-platform:
    # https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM
        run: |
          brew update
          brew install ninja cmake llvm@19

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build Bonsai
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure

  clang-tidy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Required for clang-tidy / clang-format checks.

      - name: Install dependencies
        run: |
          sudo apt-get install -y ninja-build
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19
          rm llvm.sh

      - name: Clang format
        uses: jidicula/clang-format-action@v4.14.0
        with:
          clang-format-version: '19'

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Clang tidy
        uses: ZedThree/clang-tidy-review@v0.20.1
        id: review
        if: github.event_name == 'pull_request'
        with:
          config_file: '.clang-tidy'
          build_dir: build
          lgtm_comment_body: "" # No comments upon success.

        # TODO(cgyurgyik): Enable this again when we figure out how to correctly compile_commands for clang-tidy.
        # - uses: ZedThree/clang-tidy-review/upload@v0.20.1
        # id: upload-review
        # If there are any comments, fail the check.
        # - if: steps.review.outputs.total_comments > 0
        #   run: exit 1
